targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/data/models/**
        options:
          field_rename: snake
          explicit_to_json: true
          any_map: true
          checked: true
